import json
from pathlib import Path

from destress.repo_audit import audit_repository


def test_empty_repository_scores_zero(tmp_path):
    report = audit_repository(tmp_path)
    assert report.score == 0
    assert report.grade == "F"
    assert all(not check.passed for check in report.checks)


def test_complete_repository_scores_one_hundred(tmp_path):
    files = {
        "README.md": (
            "# Example\n\nData availability: public data are available from the archive.\n"
            "Code availability: source code is available in this repository.\n"
        ),
        "LICENSE": "MIT\n",
        "pyproject.toml": "[project]\nname='example'\n",
        "CITATION.cff": "cff-version: 1.2.0\n",
        "CONTRIBUTING.md": "# Contributing\n",
        "RESULTS_MANIFEST.json": "{}\n",
        ".github/workflows/tests.yml": "name: tests\n",
        "tests/test_example.py": "def test_example(): assert True\n",
    }
    for relative, content in files.items():
        path = tmp_path / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    report = audit_repository(tmp_path)
    assert report.score == 100
    assert report.grade == "A"
    assert json.loads(report.to_json())["score"] == 100
    assert "Generated by de-stress-lab" in report.to_markdown()
    assert "Automated Reproducibility Audit" not in report.to_markdown()
    assert "100%2F100" in report.score_badge_url()


def test_project_repository_earns_a_grade():
    root = Path(__file__).resolve().parents[1]
    report = audit_repository(root)
    assert report.score >= 90
    assert report.grade == "A"
    assert report.score_badge_url().endswith("-brightgreen")
