"""Fast, dependency-light repository reproducibility readiness audit."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from urllib.parse import quote

PAID_AUDIT_URL = (
    "https://github.com/GrobeStreet/de-stress-lab/blob/main/docs/PAID_AUDIT.md"
)


@dataclass(frozen=True)
class AuditCheck:
    """One transparent, weighted readiness check."""

    key: str
    title: str
    weight: int
    passed: bool
    evidence: str
    recommendation: str

    @property
    def points(self) -> int:
        return self.weight if self.passed else 0


@dataclass(frozen=True)
class RepositoryAudit:
    """Complete free-tier repository audit result."""

    schema_version: int
    repository: str
    score: int
    maximum_score: int
    grade: str
    checks: tuple[AuditCheck, ...]
    scope: str

    def to_dict(self) -> dict:
        return {
            "schema_version": self.schema_version,
            "repository": self.repository,
            "score": self.score,
            "maximum_score": self.maximum_score,
            "grade": self.grade,
            "scope": self.scope,
            "checks": [
                {**asdict(check), "points": check.points} for check in self.checks
            ],
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2) + "\n"

    def to_markdown(self) -> str:
        lines = [
            "# Reproducibility readiness audit",
            "",
            f"**Score: {self.score}/{self.maximum_score} · Grade {self.grade}**",
            "",
            "| Check | Result | Points | Evidence |",
            "|---|---:|---:|---|",
        ]
        for check in self.checks:
            result = "PASS" if check.passed else "ACTION"
            evidence = check.evidence.replace("|", "\\|")
            lines.append(
                f"| {check.title} | {result} | {check.points}/{check.weight} | {evidence} |"
            )
        missing = [check for check in self.checks if not check.passed]
        if missing:
            lines.extend(["", "## Highest-value next actions", ""])
            for check in sorted(missing, key=lambda item: item.weight, reverse=True):
                lines.append(f"- **{check.title}:** {check.recommendation}")
        lines.extend(
            [
                "",
                "## Scope",
                "",
                self.scope,
                "",
                "## Go beyond readiness",
                "",
                "The free scan does not inspect scientific validity or safely "
                "execute the repository. For code, build, test, and provenance "
                "review, see the "
                f"[fixed-scope Automated Reproducibility Audit]({PAID_AUDIT_URL}).",
                "",
                "_Generated by de-stress-lab. This is a structural readiness scan, "
                "not certification that the scientific claims are correct._",
            ]
        )
        return "\n".join(lines) + "\n"

    def score_badge_url(self) -> str:
        color = (
            "brightgreen"
            if self.score >= 90
            else "green"
            if self.score >= 80
            else "yellowgreen"
            if self.score >= 70
            else "orange"
            if self.score >= 60
            else "red"
        )
        message = quote(f"{self.score}/100", safe="")
        return f"https://img.shields.io/badge/reproducibility-{message}-{color}"


def _existing(root: Path, candidates: tuple[str, ...]) -> list[str]:
    return [candidate for candidate in candidates if (root / candidate).exists()]


def _contains_any(root: Path, candidates: tuple[str, ...], needles: tuple[str, ...]) -> str | None:
    lowered_needles = tuple(needle.lower() for needle in needles)
    for candidate in candidates:
        path = root / candidate
        if not path.is_file() or path.stat().st_size > 2_000_000:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore").lower()
        except OSError:
            continue
        if any(needle in text for needle in lowered_needles):
            return candidate
    return None


def _check(
    key: str,
    title: str,
    weight: int,
    evidence: list[str] | str | None,
    recommendation: str,
) -> AuditCheck:
    if isinstance(evidence, list):
        rendered = ", ".join(evidence) if evidence else "Not found"
        passed = bool(evidence)
    else:
        rendered = evidence or "Not found"
        passed = evidence is not None
    return AuditCheck(key, title, weight, passed, rendered, recommendation)


def audit_repository(root: str | Path) -> RepositoryAudit:
    """Audit a repository using transparent, language-agnostic structural checks."""
    path = Path(root).resolve()
    if not path.is_dir():
        raise ValueError(f"repository path is not a directory: {path}")

    readmes = _existing(path, ("README.md", "README.rst", "README.txt", "README"))
    licenses = _existing(
        path,
        ("LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING", "COPYING.md"),
    )
    environments = _existing(
        path,
        (
            "pyproject.toml",
            "requirements.txt",
            "requirements-dev.txt",
            "environment.yml",
            "environment.yaml",
            "Pipfile.lock",
            "poetry.lock",
            "uv.lock",
            "renv.lock",
            "DESCRIPTION",
            "Project.toml",
            "Manifest.toml",
            "package-lock.json",
            "Cargo.lock",
        ),
    )
    tests = _existing(
        path,
        (
            "tests",
            "test",
            "spec",
            "pytest.ini",
            "tox.ini",
            "noxfile.py",
        ),
    )
    workflows = []
    workflow_root = path / ".github" / "workflows"
    if workflow_root.is_dir():
        workflows = [
            str(item.relative_to(path))
            for item in sorted(workflow_root.iterdir())
            if item.suffix in {".yml", ".yaml"}
        ]
    citation = _existing(path, ("CITATION.cff", "codemeta.json", "inst/CITATION"))
    community = _existing(
        path,
        (
            "CONTRIBUTING.md",
            "SUPPORT.md",
            "CODE_OF_CONDUCT.md",
            ".github/CONTRIBUTING.md",
        ),
    )
    evidence_files = []
    for candidate in (
        "RESULTS_MANIFEST.json",
        "MANIFEST.json",
        "checksums.txt",
        "SHA256SUMS",
        "predictions",
        "results",
    ):
        target = path / candidate
        if target.exists():
            evidence_files.append(candidate)
    evidence_files.extend(
        str(item.relative_to(path))
        for item in sorted(path.rglob("*.sha256"))
        if ".git" not in item.parts
    )

    searchable = (
        "README.md",
        "README.rst",
        "paper/paper.md",
        "paper.md",
        "REPORT.md",
        "docs/REPRODUCIBILITY.md",
        "docs/DATA.md",
    )
    data_statement = _contains_any(
        path,
        searchable,
        ("data availability", "data are available", "data is available", "data access"),
    )
    code_statement = _contains_any(
        path,
        searchable,
        ("code availability", "source code", "software is available", "code is available"),
    )

    checks = (
        _check(
            "readme",
            "Reader-facing README",
            10,
            readmes,
            "Add a README with purpose, installation, and a minimal working example.",
        ),
        _check(
            "license",
            "Explicit software license",
            10,
            licenses,
            "Add an OSI-approved LICENSE file so reuse terms are unambiguous.",
        ),
        _check(
            "environment",
            "Machine-readable environment",
            15,
            environments,
            "Add a dependency manifest and pin a reproducible environment or lockfile.",
        ),
        _check(
            "tests",
            "Automated tests",
            15,
            tests,
            "Add automated tests that verify the core scientific calculation.",
        ),
        _check(
            "continuous_integration",
            "Continuous integration",
            10,
            workflows,
            "Run tests automatically on pull requests with a CI workflow.",
        ),
        _check(
            "citation",
            "Citation metadata",
            5,
            citation,
            "Add CITATION.cff or CodeMeta metadata with authors and a version.",
        ),
        _check(
            "data_availability",
            "Data-availability statement",
            10,
            data_statement,
            "Document every required dataset, access restriction, and retrieval source.",
        ),
        _check(
            "code_availability",
            "Code-availability statement",
            10,
            code_statement,
            "State where the exact code version supporting the results can be accessed.",
        ),
        _check(
            "community",
            "Contribution and support path",
            5,
            community,
            "Explain how users report problems, request support, and contribute changes.",
        ),
        _check(
            "frozen_evidence",
            "Frozen evidence or result manifest",
            10,
            sorted(set(evidence_files)),
            "Publish checksums or a result manifest that binds claims to exact artifacts.",
        ),
    )
    score = sum(check.points for check in checks)
    grade = "A" if score >= 90 else "B" if score >= 80 else "C" if score >= 70 else "D" if score >= 60 else "F"
    return RepositoryAudit(
        schema_version=1,
        repository=path.name,
        score=score,
        maximum_score=100,
        grade=grade,
        checks=checks,
        scope=(
            "The free scan checks repository structure and documented reproducibility "
            "controls. It does not execute scientific claims, inspect private data, "
            "or provide peer review, regulatory assurance, or certification."
        ),
    )
